//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneShop.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ID_Application { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Phone { get; set; }
        public Nullable<int> ID_Client { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual User User { get; set; }
    }
}
