//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneShop.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int ID_Balance { get; set; }
        public string Name { get; set; }
        public string Count { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
