//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneShop.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public Phone()
        {
            this.ActRepair = new HashSet<ActRepair>();
            this.Application = new HashSet<Application>();
        }
    
        public int ID_Phone { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public Nullable<int> ID_TypePhone { get; set; }
    
        public virtual ICollection<ActRepair> ActRepair { get; set; }
        public virtual ICollection<Application> Application { get; set; }
        public virtual TypePhone TypePhone { get; set; }
    }
}
