//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneShop.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Application = new HashSet<Application>();
            this.Balance = new HashSet<Balance>();
            this.Client = new HashSet<Client>();
        }
    
        public int ID_User { get; set; }
        public string login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ID_Role { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
        public virtual ICollection<Balance> Balance { get; set; }
        public virtual ICollection<Client> Client { get; set; }
        public virtual Role Role { get; set; }
    }
}
